version: '3.7'

services:
  frontend:
    image: frontend-dev
    build: 
      context: ./frontend
    command: [npm, run, dev]
    ports:
      - 3000:3000
    env_file:
        - .env.dev
    volumes:
      - /frontend/node_modules
      - ./frontend:/app
    restart: on-failure
  backend:
    image: backend-dev
    build: 
      context: ./backend
    command: [npm, run, start:dev]
    volumes:
      - /backend/node_modules
      - ./backend:/app
    env_file: .env.dev
    ports:
      - "3001:3000"
  db:
    image: postgres:13
    env_file: .env.dev
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - backend-db:/var/lib/postgresql/data
volumes:
  next-cache:
  nest-cache:
  backend-db:
